/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const *: typeof import('@element-plus/icons-vue')
  const ElSpace: typeof import('element-plus/es')['ElSpace']
}
